server:
  port: 8080

spring:
  application:
    name: gateway-service

zuul:
  routes:
    user:
      path: /users/api/**
      serviceId: user-service
      stripPrefix: false
    organization:
      path: /organizations/api/**
      serviceId: organization-service
      stripPrefix: false
    user-Swagger:
      path: /v3/api-docs/user
      url: http://localhost:8081/v3/api-docs
      stripPrefix: false
    organizations-Swagger:
      path: /v3/api-docs/organizations
      url: http://localhost:8083/v3/api-docs
      stripPrefix: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
